# Generated by Django 4.0.3 on 2022-03-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('appointed', 'Appointed'), ('accepted', 'Accepted'), ('info_required', 'Info Required'), ('done', 'Done'), ('rejected', 'Rejected')], default='created', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_as_performer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
