# Generated by Django 4.0.3 on 2022-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer_alter_order_performer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
