# Generated by Django 4.0.3 on 2022-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_address_order_flat_number_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flat_number',
            field=models.CharField(default='не указана', max_length=100),
        ),
    ]
